version: 0.2
phases:
  install:
    commands:
    - |
        export DEBIAN_FRONTEND=noninteractive && \
        export COMPOSER_ALLOW_SUPERUSER=1

        apt-get update --fix-missing && \
        apt-get install -y --no-install-recommends apt-utils gnupg && \
        locale-gen en_US.UTF-8 && \
        update-locale

        export LANG=en_US.UTF-8 && \
        export LANGUAGE=en_US:en && \
        export LC_ALL=en_US.UTF-8 && \
        dpkg-reconfigure locales

        add-apt-repository -y ppa:ondrej/php
        apt-get update && \
        apt-get -y upgrade

        # Install PHP
        apt-get -y install php7.2-cli php7.2-curl php7.2-mbstring php7.2-intl php7.2-bcmath php7.2-xmlrpc php7.2-xml php7.2-zip php-xdebug

        # Install composer
        curl -sS https://getcomposer.org/installer | php -- && \
        php composer.phar config -g repos.packagist composer https://packagist.jp && \
        php composer.phar global require hirak/prestissimo

  pre_build:
    commands:
    - bash -c "$(curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/master/install)"
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
    - echo Build started on `date`
    - echo Installing composer deps
    - php composer.phar install --no-progress --no-suggest
    - echo Testing...
    - ./vendor/bin/phpunit
    - echo Building the Docker image...
    - docker build -t app .
    - docker build -t web -f docker/web.dockerfile docker
    - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
    - docker tag $IMAGE_REPO_NAME-web:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME-web:latest

  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
